#ifndef CONSTANTS
#define CONSTANTS

#define MAXIMUM_NUM_OF_PRODUCTS 100
#define MAXIMUM_NUM_OF_TEAMS 100
#define MAXIMUM_NUM_OF_CUSTOMERS 100
#define BETWEEN_MANGER_CHECKS 3
#define TIME_TO_EACH_EMPLOYEE_TO_RESTOCK 3
#define BETWEEN_EMPLOYEES_RESTOCK 100000  //time between each employee to arrive to and start restock usleep(BETWEEN_EMPLOYEES_RESTOCK)
#define BETWEEN_EACH_PICK_FOR_CUSTOMER 17

#endif
